// One `tileset.json`, normalised into flat tiles.
//
// Normalising means: composing the transform chain, reducing three bounding
// volume types to one, inheriting `refine`, resolving content URIs against the
// document that declared them, and applying the two corrections real tilesets
// need. Everything it had to fix comes back as a warning rather than a throw —
// the rule this repo has held since the first loader.

import type { PointCloudWarning } from "@voxelkloud/core";
import {
  IDENTITY,
  boundingVolumeToBounds,
  isRegion,
  looksEcef,
  multiply,
} from "./bounds.js";
import type { BoundingVolumeJson, Mat4, VolumeBounds } from "./bounds.js";
import type { ImplicitContext, ImplicitCoord } from "./implicit.js";
import type {
  ImplicitTilingJson,
  RefineMode,
  TileJson,
  TilesetJson,
  TilesetWarningCode,
} from "./types.js";

export type TilesetWarning = PointCloudWarning<TilesetWarningCode>;

/** Content this driver knows how to turn into points. */
export type ContentKind = "pnts" | "gltf" | "tileset" | "unsupported";

export interface Tile {
  readonly index: number;
  /** Slash path of child ordinals from the ROOT of the whole tileset. */
  readonly name: string;
  readonly level: number;
  readonly bounds: VolumeBounds;
  /**
   * The tile's bounding volume as WRITTEN, before the transform.
   *
   * Kept only because implicit tiling subdivides it: halving an oriented box
   * happens in the box's own frame, and `bounds` has already been flattened to
   * an axis-aligned envelope in world space, which cannot be halved back.
   */
  readonly volumeJson: BoundingVolumeJson | undefined;
  /**
   * The tile's OWN geometric error, monotonically clamped. What a CHILD of this
   * tile is scored by — see {@link refinementError}.
   */
  readonly geometricError: number;
  /**
   * THE QUANTITY THE SCHEDULER SCORES THIS TILE BY: the error of the
   * representation that would stand if this tile were NOT drawn, i.e. the
   * PARENT's own geometric error. The root gets the tileset's.
   *
   * Shifted one level on purpose, and DEC-T2 is the argument. In short: the
   * scheduler admits a child when `error(child) * projFactor >= target`, and a
   * 3D Tiles leaf has `geometricError: 0`, so the unshifted quantity makes the
   * finest level of every tileset unreachable — silently, with no error and no
   * warning. Shifted, the same comparison becomes Cesium's rule, which is
   * "refine when the CURRENT representation is too coarse".
   */
  readonly refinementError: number;
  /**
   * Pre-read point pitch, world units. A tiler sets `geometricError` to roughly
   * the point spacing, so the tile's own error is the best guess available
   * before its content is decoded; a leaf declares 0 and inherits half its
   * parent's. Replaced by the MEASURED pitch once the content lands.
   */
  readonly pitch: number;
  readonly refine: RefineMode;
  /** Composed from the root down. */
  readonly transform: Mat4;
  /** Absolute, resolved against the document that declared it. */
  readonly contentUri: string | undefined;
  readonly contentKind: ContentKind;
  /**
   * The content URI as WRITTEN, when it is an implicit TEMPLATE.
   *
   * A template is not a URL and must not be resolved as one: `new URL()`
   * percent-encodes the braces, and `{level}` comes back as `%7Blevel%7D`,
   * which then substitutes into nothing. So an implicit tile keeps its template
   * here and leaves `contentUri` undefined until a coordinate fills it in.
   */
  readonly contentTemplate: string | undefined;
  /** The document this tile came from, for resolving its templates. */
  readonly documentUrl: string;
  readonly implicitTiling: ImplicitTilingJson | undefined;
  /**
   * Set only on a tile GENERATED by the implicit rule, never on one a document
   * wrote. Carries the rule and this tile's place in the grid, which is what
   * lets a placeholder at the bottom of a subtree fetch the next one.
   */
  readonly implicit?:
    | { readonly context: ImplicitContext; readonly coord: ImplicitCoord }
    | undefined;
  readonly parentIndex: number | undefined;
  readonly childIndices: number[];
}

export interface ParsedTileset {
  readonly tiles: Tile[];
  readonly warnings: TilesetWarning[];
  /** `asset.version`, verbatim. */
  readonly version: string;
  /**
   * Whether the tileset is GEOREFERENCED, i.e. its coordinates are ECEF.
   *
   * Two ways to be, and the second is the common one. A `region` volume says it
   * outright — it is defined in EPSG:4979, so what it constrains is EPSG:4978.
   * But most tilesets a pipeline emits use a LOCAL box under a root transform
   * whose translation is an ECEF position, and never write a region at all; see
   * `looksEcef`. Missing that second case calls a georeferenced tileset local,
   * which is the difference between a cloud that can be placed next to another
   * and one that cannot.
   */
  readonly georeferenced: boolean;
}

export interface ParseTilesetOptions {
  /** Absolute URL of the document, for resolving content URIs. */
  readonly baseUrl: string;
  /** Index the root tile is given. Non-zero when stitching an external tileset. */
  readonly startIndex?: number;
  /** Name prefix for the root tile. */
  readonly namePrefix?: string;
  /** Level the root tile sits at, when grafted under another tileset. */
  readonly startLevel?: number;
  /** Transform inherited from the referring tile. */
  readonly parentTransform?: Mat4;
  /** The referring tile's own geometric error, which scores this root. */
  readonly parentGeometricError?: number;
  readonly parentIndex?: number;
  readonly parentRefine?: RefineMode;
}

function warn(
  list: TilesetWarning[],
  code: TilesetWarningCode,
  message: string,
  // `path` is REQUIRED by the warning contract, so a tileset-wide anomaly names
  // the document rather than an empty string.
  path = "tileset.json",
): void {
  list.push({ code, message, path });
}

/** `.pnts`, a glTF, another tileset, or something this driver will not read. */
export function classifyContent(uri: string): ContentKind {
  const path = uri.split(/[?#]/)[0] ?? "";
  const dot = path.lastIndexOf(".");
  const ext = dot < 0 ? "" : path.slice(dot).toLowerCase();
  if (ext === ".pnts") return "pnts";
  if (ext === ".glb" || ext === ".gltf") return "gltf";
  if (ext === ".json") return "tileset";
  // No extension at all is the templated-URI case, which implicit tiling
  // resolves before it gets here, and the served-without-extension case, which
  // only the bytes can settle. Both are decided by sniffing the payload.
  if (ext === "") return "gltf";
  return "unsupported";
}

function resolveUri(base: string, uri: string): string {
  try {
    return new URL(uri, base).toString();
  } catch {
    return uri;
  }
}

function pickContent(
  tile: TileJson,
  warnings: TilesetWarning[],
  path: string,
): { uri: string | undefined; kind: ContentKind } {
  const list: readonly { readonly uri?: string; readonly url?: string }[] =
    tile.contents ?? (tile.content !== undefined ? [tile.content] : []);
  if (list.length === 0) return { uri: undefined, kind: "unsupported" };

  const usable = list
    .map((c) => c.uri ?? c.url)
    .filter((u): u is string => typeof u === "string" && u.length > 0)
    .map((u) => ({ uri: u, kind: classifyContent(u) }));

  const first = usable.find((c) => c.kind !== "unsupported") ?? usable[0];
  if (first === undefined) return { uri: undefined, kind: "unsupported" };

  if (usable.length > 1) {
    warn(
      warnings,
      "content-multiple",
      `Tile has ${usable.length} contents; reading ${first.uri} and ignoring ` +
        `the rest. A point cloud tile with several contents is unusual, and ` +
        `nothing here can merge them into one point layer.`,
      path,
    );
  }
  if (first.kind === "unsupported") {
    warn(
      warnings,
      "content-unsupported",
      `Tile content ${first.uri} is not point cloud content this driver reads ` +
        `(.pnts, .glb/.gltf, or an external tileset). The tile will draw ` +
        `nothing; its children, if any, are still traversed.`,
      path,
    );
  }
  return first;
}

/**
 * Walk one tileset document into flat tiles.
 *
 * Does NOT follow external tilesets or implicit subtrees — both need bytes, and
 * nothing in this package fetches. A tile that refers to either is returned
 * with its `contentUri` or `implicitTiling` set, and the caller decides.
 */
export function parseTileset(
  json: TilesetJson,
  options: ParseTilesetOptions,
): ParsedTileset {
  const warnings: TilesetWarning[] = [];
  const tiles: Tile[] = [];
  const base = options.baseUrl;
  const startIndex = options.startIndex ?? 0;
  const version = json.asset?.version ?? "";
  if (version !== "1.0" && version !== "1.1") {
    warn(
      warnings,
      "tileset-version-unknown",
      `asset.version is ${version === "" ? "absent" : `"${version}"`}; this ` +
        `driver reads 1.0 and 1.1 and will treat it as 1.1.`,
    );
  }

  let georeferenced = false;

  const rootJson = json.root;
  if (rootJson === undefined) {
    return { tiles, warnings, version, georeferenced };
  }

  const rootRefine = parseRefine(rootJson.refine);
  if (rootRefine === undefined && options.parentRefine === undefined) {
    warn(
      warnings,
      "refine-missing-on-root",
      `The root tile declares no "refine"; the spec requires it. Assuming ` +
        `"REPLACE", which is what a tile hierarchy means by default.`,
    );
  }

  // The tileset's own geometric error scores the ROOT: it is the error of
  // drawing nothing at all. When this document is grafted under a tile of
  // another one, that tile's error takes the job instead.
  const topError =
    options.parentGeometricError ??
    (typeof json.geometricError === "number" && json.geometricError >= 0
      ? json.geometricError
      : Number.POSITIVE_INFINITY);

  interface Frame {
    readonly json: TileJson;
    readonly parentIndex: number | undefined;
    readonly parentError: number;
    readonly parentTransform: Mat4;
    readonly parentRefine: RefineMode;
    readonly level: number;
    readonly name: string;
  }

  const stack: Frame[] = [
    {
      json: rootJson,
      parentIndex: options.parentIndex,
      parentError: topError,
      parentTransform: options.parentTransform ?? IDENTITY,
      parentRefine: rootRefine ?? options.parentRefine ?? "REPLACE",
      level: options.startLevel ?? 0,
      name: options.namePrefix ?? "r",
    },
  ];

  while (stack.length > 0) {
    const frame = stack.pop()!;
    const t = frame.json;
    const index = startIndex + tiles.length;

    const transform =
      t.transform !== undefined && t.transform.length >= 16
        ? multiply(frame.parentTransform, t.transform)
        : frame.parentTransform;

    if (isRegion(t.boundingVolume)) georeferenced = true;

    let bounds = boundingVolumeToBounds(t.boundingVolume, transform);
    if (bounds === undefined) {
      // Fall back to the parent's box rather than dropping the subtree: an
      // unreadable volume is a tile that culls wrongly, a missing tile is a
      // hole. The parent's box always contains the child's, by the spec.
      const parent = frame.parentIndex;
      const inherited =
        parent !== undefined ? tiles[parent - startIndex]?.bounds : undefined;
      warn(
        warnings,
        t.boundingVolume === undefined
          ? "tile-missing-bounding-volume"
          : "tile-unreadable-bounding-volume",
        `Tile ${frame.name} has no bounding volume this driver can read; ` +
          `using its parent's, which contains it by the spec.`,
        frame.name,
      );
      if (inherited === undefined) continue;
      bounds = inherited;
    }

    let own = typeof t.geometricError === "number" ? t.geometricError : undefined;
    if (own === undefined || !(own >= 0)) {
      warn(
        warnings,
        "tile-missing-geometric-error",
        `Tile ${frame.name} declares no usable geometricError; inheriting ` +
          `half its parent's, which is what a halving hierarchy would give.`,
        frame.name,
      );
      own = Number.isFinite(frame.parentError) ? frame.parentError / 2 : 0;
    }
    // MONOTONICITY IS THE DRIVER'S JOB, not the scheduler's: best-first is only
    // correct because the key cannot rise on the way down, and real files
    // violate the spec's own rule. Clamp and say so.
    if (own > frame.parentError) {
      warn(
        warnings,
        "geometric-error-not-monotonic",
        `Tile ${frame.name} declares geometricError ${own}, larger than its ` +
          `parent's ${frame.parentError}. Clamped to the parent's.`,
        frame.name,
      );
      own = frame.parentError;
    }

    const refine = parseRefine(t.refine) ?? frame.parentRefine;
    const content = pickContent(t, warnings, frame.name);
    // An implicit tile's content URI is a template, not a location.
    const templated = t.implicitTiling !== undefined && content.uri !== undefined;

    const tile: Tile = {
      index,
      name: frame.name,
      level: frame.level,
      bounds,
      volumeJson: t.boundingVolume,
      geometricError: own,
      refinementError: frame.parentError,
      // A leaf declares 0 and would draw points of zero size; half the parent's
      // is what the next level down would have carried.
      pitch: own > 0 ? own : Number.isFinite(frame.parentError) ? frame.parentError / 2 : 1,
      refine,
      transform,
      contentUri:
        templated || content.uri === undefined
          ? undefined
          : resolveUri(base, content.uri),
      contentKind: templated ? "unsupported" : content.kind,
      contentTemplate: templated ? content.uri : undefined,
      documentUrl: base,
      implicitTiling: t.implicitTiling,
      parentIndex: frame.parentIndex,
      childIndices: [],
    };
    tiles.push(tile);
    if (tiles.length === 1 && looksEcef(bounds.centreX, bounds.centreY, bounds.centreZ)) {
      georeferenced = true;
    }
    if (frame.parentIndex !== undefined) {
      tiles[frame.parentIndex - startIndex]?.childIndices.push(index);
    }

    // Pushed in reverse so the children come out in DECLARED order, which is
    // the order `childIndices` records and the order a name refers to.
    const kids = t.children ?? [];
    for (let c = kids.length - 1; c >= 0; c--) {
      stack.push({
        json: kids[c]!,
        parentIndex: index,
        parentError: own,
        parentTransform: transform,
        parentRefine: refine,
        level: frame.level + 1,
        name: `${frame.name}/${c}`,
      });
    }
  }

  for (const ext of json.extensionsRequired ?? []) {
    warn(
      warnings,
      "extension-unsupported",
      `The tileset REQUIRES the extension "${ext}", which this driver does ` +
        `not implement. Tiles that depend on it will fail to decode.`,
    );
  }

  return { tiles, warnings, version, georeferenced };
}

function parseRefine(value: string | undefined): RefineMode | undefined {
  if (value === undefined) return undefined;
  // Case-insensitive on purpose: 1.0 said uppercase, files in the wild write
  // "add", and rejecting them buys nothing.
  const v = value.toUpperCase();
  return v === "ADD" ? "ADD" : v === "REPLACE" ? "REPLACE" : undefined;
}
